articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.articles,name='list'),
    path('<slug:article_name>',views.ind_article,name='detail')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/',views.about),
    path('articles/',include('articles.urls'))
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

# Create your models here.


class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

    def short(self):
        return self.body[:50]+' ...'    

articles/views.py
from django.shortcuts import render
from .models import Articles
from django.http import HttpResponse
# Create your views here.

def articles(request):
    articles = Articles.objects.all().order_by('date')
    return render(request,'articles/article_view.html',{'articles':articles})

def ind_article(request,article_name):
    article = Articles.objects.get(slug=article_name)
    return render(request,'articles/article_detail.html',{'article':article})

myproject/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request,'homepage.html')

def about(request):
    return render(request,'aboutpage.html')

articles/templates/articles/article_detail.html
{% extends 'basic_layout.html' %}


{% block content %}

  <div>
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
    <hr>
  </div>

{% endblock %}

articles/templates/articles/article_view.html
{% extends 'basic_layout.html' %}

{% block content %}

    <h1 style='text-decoration:underline;font-size:60px;margin-bottom:20px;'>Articles</h1>
    <div class="articles">
      {% for article in articles %}
        <div class="article">
          <h1><a href="{% url 'articles:detail' article_name=article.slug %}">{{article.title}}</a></h1>
          <p>{{article.short}}</p>
          <p>{{article.date}}</p>
        </div>
      {% endfor %}
    </div>

{% endblock %}

templates/aboutpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About Page</title>
  </head>
  <body>
    <h1>This is an about page of my django project</h1>
    <p>Yey!!!!!</p>
  </body>
</html>

templates/basic_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'main.jpg' %}">
  </head>
  <body>
     <div class="wrapper">
       <h1><a href="{% url 'articles:list' %}"><img src='{% static 'logo.png' %}'></a>
       {% block content %}

       {% endblock %}
     </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HomePage</title>
  </head>
  <body style='text-align:center'>
    <h1>This is Home Page</h1>
    <p>First django project</p>
  </body>
</html>